let albania = {
  name: "Albania",
  flag:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/125px-Flag_of_Albania.svg.png",
  geoLocaltion:
    "https://upload.wikimedia.org/wikipedia/commons/d/d5/Albania_%28orthographic_projection%29.svg",
  capital: "Tirana, 41°19′N 19°49′E",
  "Official languages": "Albanian",
  "Recognised minority languages": "GreekAromanianMacedonianothers",
  "Demonym(s)": "Albanian",
  Government: "Unitary parliamentary constitutional republic",
  President: "Ilir Meta",
  "Prime Minister": "Edi Rama",
  Legislature: "Elections, Assembly (speakers), Members, Opposition, ",
  "Principality of Arbanon": "1190",
  "Kingdom of Albania": "1 September 1928",
  "Princedom of Albania": "1368",
  "League of Lezhë": "2 March 1444",
  "Proclamation of independence from the Ottoman Empire": "28 November 1912",
  "Principality of Albania (Recognised)": "29 July 1913",
  "1st Republic of Albania": "31 January 1925",
  "2nd Republic of Albania": "11 January 1946",
  "3rd Republic of Albania": "28 December 1976",
  "4th Republic of Albania, Current constitution":
    "29 April 1991, , 28 November 1998",
  Total: "$16.753 billion[3]",
  "Water (%)": "4.7",
  "January 2020 estimate": " 2,845,955[1]",
  "2011 census": "2,821,977[2]",
  Density: "98/km2 (253.8/sq mi) (63rd)",
  "GDP (PPP)": "2020 estimate",
  "Per capita": "$5,847[3]",
  "GDP (nominal)": "2020 estimate",
  "Gini (2017)": " 33.2[4], medium",
  "HDI (2018)": " 0.791[5], high · 69th",
  Currency: "Lek (ALL)",
  "Time zone": "UTC+1 (CET)",
  "Summer (DST)": "UTC+2 (CEST)",
  "Date format": "dd/mm/yyyy",
  "Driving side": "right",
  "Calling code": "+355",
  "ISO 3166 code": "AL",
  "Internet TLD": ".al",
};
