let andorra = {
  name: "Andorra",
  flag:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/125px-Flag_of_Andorra.svg.png",
  geoLocation:
    "https://upload.wikimedia.org/wikipedia/commons/1/12/Location_Andorra_Europe.png",
  capital: "Andorra la Vella, 42°30′N 1°31′E, Coordinates: 42°30′N 1°31′E",
  "Official languages": "Catalanb",
  "Ethnic groups (2017[3])":
    "48.8% Andorrans, 25.1% Spanish, 12% Portuguese, 4.4% French, 9.7% others",
  Religion: "Roman Catholicism[4][5]",
  "Demonym(s)": "Andorran",
  Government: "Unitary parliamentary semi-elective diarchy",
  "Co-Princes": "Joan Enric Vives Sicília, Emmanuel Macron",
  Representatives: "Josep Maria Mauri, Patrick Strzoda",
  "Prime Minister": "Xavier Espot Zamora",
  "General Syndic": "Roser Suñé Pascuet",
  Legislature: "General Council",
  "from Aragon": "8 September 1278[6][7]",
  "from the French Empire": "1814",
  Constitution: "2 February 1993",
  Total: "$3.237 billion[9]",
  "Water (%)": "0.26 (121.4 ha)c",
  "2020 estimate": " 77,543[8] (203rd)",
  Density: "179.8/km2 (465.7/sq mi) (71st)",
  "GDP (nominal)": "2018 estimate",
  "Per capita": "$42,035",
  "Gini (2003)": "27.21d, low",
  "HDI (2018)": " 0.857[10], very high · 36th",
  Currency: "Euroe (EUR)",
  "Time zone": "UTC+01 (CET)",
  "Summer (DST)": "UTC+02 (CEST)",
  "Driving side": "right[11]",
  "Calling code": "+376",
  "ISO 3166 code": "AD",
  "Internet TLD": ".adf",
};
