let belgium = {
  name: "Belgium",
  flag:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/125px-Flag_of_Belgium.svg.png",
  geoLocation:
    "https://upload.wikimedia.org/wikipedia/commons/6/67/EU-Belgium.svg",
  capital: "Brussels, 50°51′N 4°21′E",
  "Largest city": "Brussels",
  "Official languages": "Dutch, French, German",
  "Religion (2018[1])":
    "62.8% Christianity, 29.3% No religion, 6.8% Islam, 1.1% Other religions",
  "Demonym(s)": "Belgian",
  Government: "Federal parliamentary, constitutional monarchy[2]",
  Monarch: "Philippe",
  "Prime Minister": "Sophie Wilmès",
  Legislature: "Federal Parliament",
  "Upper house": "Senate",
  "Lower house": "Chamber of Representatives",
  Declared: "4 October 1830",
  Recognised: "19 April 1839",
  Total: "$533 billion[5] (23rd)",
  "Water (%)": "6.5",
  "2020 estimate": "11,492,641 [4] (81st)",
  Density: "376/km2 (973.8/sq mi) (22nd)",
  "GDP (PPP)": "2018 estimate",
  "Per capita": "$46,724[5] (17th)",
  "GDP (nominal)": "2018 estimate",
  "Gini (2018)": " 25.6[6], low",
  "HDI (2019)": " 0.919[7], very high · 17th",
  Currency: "Euro (€) (EUR)",
  "Time zone": "UTC+1 (CET)",
  "Summer (DST)": "UTC+2 (CEST)",
  "Driving side": "right",
  "Calling code": "+32",
  "ISO 3166 code": "BE",
  "Internet TLD": ".be",
};
