let bosniaAndHerzegovina = {
  name: "Bosnia and Herzegovina",
  flag:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/125px-Flag_of_Bosnia_and_Herzegovina.svg.png",
  geoLocation:
    "https://upload.wikimedia.org/wikipedia/commons/9/94/Europe-Bosnia_and_Herzegovina.svg",
  capital: "Sarajevo[1], 43°52′N 18°25′E",
  "Official languages (state level)": "None[1]",
  "Official languages (entity level)": "Bosnian, Serbian, Croatian",
  "Demonym(s)": "Bosnian, Herzegovinian[2][3][4]",
  Government: "Federal parliamentary, constitutional republic[5]",
  "High Representative": "Valentin Inzkoa",
  "Chairman of the Presidency": "Šefik Džaferovićb",
  "Members of the Presidency": "Željko Komšićc, Milorad Dodikd",
  "Chairman of the Council of Ministers": "Zoran Tegeltija",
  Legislature: "Parliamentary Assembly",
  "Upper house": "House of Peoples",
  "Lower house": "House of Representatives",
  "Bosnia (early medieval polity)": "c. 7th century",
  "Banate of Bosnia": "1154",
  "Kingdom of Bosnia": "1377",
  "Ottoman conquest": "1463",
  "Austro-Hungarian conquest and 1908 annexation": "1878",
  "Creation of Yugoslavia": "1 December 1918",
  "State Anti-fascist Council for the National Liberation of Bosnia and Herzegovina":
    "25 November 1943",
  "Independence from Yugoslavia": "1 March 1992",
  "Washington Agreement": "18 March 1994",
  "Dayton Agreement": "14 December 1995",
  Total: "$21.023 billion[8]",
  "Water (%)": "1.4%",
  "2019 estimate": "3,301,000[6] (135th)",
  "2016 census": "3,511,372[7]",
  Density: "69/km2 (178.7/sq mi)",
  "GDP (PPP)": "2020 estimate",
  "Per capita": "$6,056[8]",
  "GDP (nominal)": "2020 estimate",
  "Gini (2011)": "33.8[9], medium · 47th",
  "HDI (2018)": " 0.769[10], high · 75th",
  Currency: "Convertible mark (BAM)",
  "Time zone": "UTC+01 (CET)",
  "Summer (DST)": "UTC+02 (CEST)",
  "Date format": "dd. mm. yyyy. (CE)",
  "Driving side": "right",
  "Calling code": "+387",
  "ISO 3166 code": "BA",
  "Internet TLD": ".ba",
};
