let faroeIslands = {
  name: "Faroe Islands",
  flag:
    "https://upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_the_Faroe_Islands.svg",
  geoLocation:
    "https://upload.wikimedia.org/wikipedia/commons/b/bc/Europe-Faroe_Islands.svg",
  "Sovereign state": "Denmark",
  "Unified with Norway": "c. 1035",
  "Cession to Denmark": "14 January 1814",
  "Home rule": "1 April 1948",
  "Further autonomy": "29 July 2005[1]",
  capital: "Tórshavn, 62°00′N 06°47′W",
  "Official languages": "Faroese[2]Danish",
  "Ethnic groups": "Faroe Islanders",
  Religion: "Christianity (Church of the Faroe Islands)",
  "Demonym(s)": "Faroe IslanderFaroese",
  Government:
    "Devolved government within a parliamentary constitutional monarchy",
  Monarch: "Margrethe II",
  "High Commissioner": "Lene Moyell Johansen",
  "Prime Minister": "Bárður á Steig Nielsen",
  Legislature: "Løgting",
  Folketing: "2 members",
  Total: "$3 billion[5] (not ranked)",
  "Water (%)": "0.5",
  "Highest elevation": "882 m (2,894 ft)",
  "2020 estimate": "52,110[3] (214th)",
  "2020 census": "52,337[4]",
  Density: "37.0/km2 (95.8/sq mi)",
  "GDP (nominal)": "2017 estimate",
  "Per capita": "$61,325 (not ranked)",
  "Gini (2015)": " 23.3[6], low · 2",
  "HDI (2008)": "0.950[7], very high",
  Currency: "Faroese króna (DKK)",
  "Time zone": "UTC±00:00 (WET)",
  " Summer (DST)": "UTC+01:00 (WEST)",
  "Date format": "dd-mm-yyyy",
  "Driving side": "right",
  "Calling code": "+298",
  "Postal codes": "FO-xxx",
  "ISO 3166 code": "FO",
  "Internet TLD": ".fo",
  "Record high °C (°F)": "11.6, (52.9)",
  "Average high °C (°F)": "5.8, (42.4)",
  "Daily mean °C (°F)": "4.0, (39.2)",
  "Average low °C (°F)": "1.7, (35.1)",
  "Record low °C (°F)": "−8.8, (16.2)",
  "Average precipitation mm (inches)": "157.7, (6.21)",
  "Average precipitation days (≥ 0.1 mm)": "26",
  "Average snowy days": "8.3",
  "Average relative humidity (%)": "89",
  "Mean monthly sunshine hours": "14.5",
  History: "TimelineBritish occupationFæreyinga saga",
  Geography:
    "GeologyLakesMountainsCitiesTownsMunicipalitiesRegions, , Islands\t, BorðoyEysturoyFugloyHesturKalsoyKolturKunoyLítla DímunMykinesNólsoySandoySkúvoyStóra DímunStreymoySuðuroySvínoyVágarViðoy",
  Islands:
    "BorðoyEysturoyFugloyHesturKalsoyKolturKunoyLítla DímunMykinesNólsoySandoySkúvoyStóra DímunStreymoySuðuroySvínoyVágarViðoy",
  Politics:
    "Løgting (parliament) SpeakerPolitical partiesPrime Minister Deputy Prime MinisterCabinetIndependence movement",
  Economy:
    "CompaniesEconomic historyEnergyKróna (currency)Postal systemTaxationTelecommunicationsTourismTrade unionsTransport",
  Society:
    "Faroe IslandersDemographicsEducationLanguageLGBT rightsReligionWhaling, , Culture\t, ArtCinemaCuisineLiteratureMediaMusicÓlavsøka (holiday)Sport, , Symbols\t, AnthemCoat of armsMerkið (flag)",
  Culture: "ArtCinemaCuisineLiteratureMediaMusicÓlavsøka (holiday)Sport",
  Symbols: "AnthemCoat of armsMerkið (flag)",
  States: ",  Denmark,  Finland,  Iceland,  Norway,  Sweden",
  "Autonomous countries": ",  Åland Islands,  Faroe Islands,  Greenland",
  "Special status/Cultural area": ",  Svalbard,  Sápmi",
  Related:
    ", Climate of the Nordic countries, Comparison of the Nordic countries, Nordic Council, Nordic Cross flag, Subdivisions of the Nordic countries, LGBT in the Nordic countries, Nordic diplomatic missions",
  "See also": ", Norsemen, Old Norse, Nordic identity in Estonia, Scandinavia",
  "East Indies":
    "Governorate General, Fort Dansborg, Settlements, Frederiksnagore (Serampore), Danmarksnagore (Gondalpara), Oddeway Torre (Malabar Coast), Frederiksøerne (Nicobar Islands), Factories, Calicut (Kozhikode), Colachel, Masulipatnam, Trading posts, Balasore, Oddeway Torre (Malabar Coast), Pipli",
  "Governorate General": ", Fort Dansborg",
  Settlements: ", Haabets Colonie",
  Factories: ", Calicut (Kozhikode), Colachel, Masulipatnam",
  "Trading posts":
    "Egede and Paarss, Godt-Haab, Moravian missions, Lichtenfels, Neu-Herrnhut, Severin, Christianshaab, Frederikshaab, Jacobshavn, General Trade Company, Christianshaab, Claushavn, Egedesminde, Fiskenæsset, Frederikshaab, Godhavn, Godt-Haab, Holsteinsborg, Jacobshavn, Julianehaab, Lichtenfels, Neu-Herrnhut, Ritenbenck, Sukkertoppen, Umanak, Upernavik",
  "West Indies": "Colonies in the Caribbean, St. Thomas, St. John, St. Croix",
  "Colonies in the Caribbean": ", St. Thomas, St. John, St. Croix",
  "Gold Coast":
    "Trading posts in Africa, Augustaborg, Carlsborg, Christiansborg, Frederiksborg, Fredensborg, Kongensten, Prinsensten, William",
  "Trading posts in Africa":
    ", Augustaborg, Carlsborg, Christiansborg, Frederiksborg, Fredensborg, Kongensten, Prinsensten, William",
  "North GreenlandandSouth Greenland":
    "Trading postsEgede and Paarss, Godt-Haab, Moravian missions, Lichtenfels, Neu-Herrnhut, Severin, Christianshaab, Frederikshaab, Jacobshavn, General Trade Company, Christianshaab, Claushavn, Egedesminde, Fiskenæsset, Frederikshaab, Godhavn, Godt-Haab, Holsteinsborg, Jacobshavn, Julianehaab, Lichtenfels, Neu-Herrnhut, Ritenbenck, Sukkertoppen, Umanak, Upernavik",
  "Egede and Paarss": ", Godt-Haab",
  "Moravian missions": ", Lichtenfels, Neu-Herrnhut",
  Severin: ", Christianshaab, Frederikshaab, Jacobshavn",
  "General Trade Company":
    ", Christianshaab, Claushavn, Egedesminde, Fiskenæsset, Frederikshaab, Godhavn, Godt-Haab, Holsteinsborg, Jacobshavn, Julianehaab, Lichtenfels, Neu-Herrnhut, Ritenbenck, Sukkertoppen, Umanak, Upernavik",
  "Until 1850": ", Gold Coast",
  "Until 1869": ", East Indies",
  "Until 1874": ", Iceland3",
  "Until 1917": ", West Indies",
  "Until 1948": ", Faroe Islands3",
  "Until 1953": ", Greenland3",
  "The unity of the Realm": ",  Denmark,  Faroe Islands,  Greenland",
  "Full members": ",  Denmark,  Finland,  Iceland,  Norway,  Sweden",
  "Associate members": ",  Åland Islands,  Faroe Islands,  Greenland",
  "Observer / offices":
    ",  Sápmi,  Estonia (identity),  Latvia,  Lithuania,  Schleswig-Holstein",
  Denmark: ", Faroe Islands, Greenland",
  France:
    ", Clipperton Island, French Polynesia, French Southern and Antarctic Lands, Adélie Land, Île Amsterdam, Crozet Islands, Îles Éparses, Kerguelen Islands, Île Saint-Paul, New Caledonia, Saint Barthélemy, Saint Martin, Saint Pierre and Miquelon, Wallis and Futuna",
  Netherlands: ", Aruba, Caribbean Netherlands, Curaçao, Sint Maarten",
  "Authority control ":
    "BNF: cb15311196z (data)GND: 4016258-8LCCN: n79035921MusicBrainz: 9ed3be5f-d54c-3add-a6a6-76c0cca54fd8NARA: 10044824NKC: ge129139NLI: 000974970SELIBR: 146102SUDOC: 196422256VIAF: 263513342WorldCat Identities: lccn-n79035921",
};
